CREATE TABLE [dbo].[HeatMapItem]
(
	[HeatMapItemID]		INT				IDENTITY (1, 1) NOT NULL,
	[KPIID]				INT				NOT NULL,
	[StartTime]			DATETIME		NULL,
	[EndTime]			DATETIME		NULL,
	[RecordStatus]		CHAR (1)		NOT NULL,
	[CreatedDate]		DATETIME		NOT NULL,
	[CreatedBy]			NVARCHAR (60)	NOT NULL,
	[ModifiedDate]		DATETIME		NOT NULL,
	[ModifiedBy]		NVARCHAR (60)	NOT NULL,
	PRIMARY KEY CLUSTERED ([HeatMapItemID] ASC),
	CONSTRAINT FK_HeatMapItem_KPI FOREIGN KEY (KPIID) REFERENCES [KPI](KPIID)
)
