CREATE TABLE [dbo].[KPI] (
[KPIID]  INT                   IDENTITY (1, 1) NOT NULL,
[KPIDescription]               NVARCHAR (60)   NOT NULL,
[CheckListTypeId]                INT           NOT NULL  DEFAULT 3,
[Measure]                      NVARCHAR (50)   NULL,
[Standard]                     NVARCHAR (50) NULL,
[AlertLevel]                   NVARCHAR (500) NULL,
[KPIMeasureID]                 INT  NOT NULL,
[IsHeatMapItem]                BIT NULL,
[HeatMapScore]                 INT NULL,
[IsUniversal]                  BIT NULL,
[RecordStatus]                 CHAR (1)       NOT NULL,
[CreatedDate]                  DATETIME       NOT NULL,
[CreatedBy]                    NVARCHAR (60)  NOT NULL,
[ModifiedDate]                 DATETIME       NOT NULL,
[ModifiedBy]                   NVARCHAR (60)  NOT NULL,
PRIMARY KEY CLUSTERED ([KPIID] ASC),
CONSTRAINT FK_KPI_CHECKLISTTYPEID  FOREIGN KEY (CheckListTypeId) REFERENCES [CheckListType](CheckListTypeID),
CONSTRAINT FK_KPI_KPIMEASUREID  FOREIGN KEY (KPIMeasureID) REFERENCES [KPIMeasure](KPIMeasureID),
);
