export const VALIDATION_MESSAGES = {
    WARN: 'warn',
    SUCCESS: 'success',
    ERROR: 'error',
    INFO : 'info',
    SAVED_SUCCESS: 'Saved Successfully',
    VALIDATION_SUMMARY: 'Validation Failed',
    SITE_EXISTS: 'The Site already exists',
    SITE_CODE_EXISTS: 'The Site Acronym already exists',
    BUSINESSUNIT_EXISTS: 'The Business Unit already exists',
    SPECIALTY_EXISTS: 'The Specialty already exists',
    PAYER_EXISTS: 'The Payer already exists',
    BUSINESS_SITE_DROPDOWN_ERROR: 'Select a Business Site',
    SPECIALTY_DROPDOWN_ERROR: 'Select a Specialty',
    SYSTEM_DROPDOWN_ERROR: 'Select a System',
    BUSINESSUNIT_DROPDOWN_ERROR: 'Select a Business Unit',
    SITE_REQUIRED: 'Site Name is Required',
    SITE_ACR_REQUIRED: 'Site Acronym is Required',
    SITE_ACR_LENGTH: 'Site Acronym length shouldn\'t be greater than 3',
    SPECILTY_REQUIRED: 'Specialty Name is Required',
    BUSINESSUNIT_REQUIRED: 'Business Unit Name is Required',
    PAYERS_REQUIRED: 'Payer Name is required',
    CLIENT_DATA_PERCENTAGE_CASH: 'Percentage of Cash Format should be ##.##',
    SYSTEM_REQUIRED: 'System Name is required',
    SYSTEM_EXISTS: 'The System already exits',
    MEASURE_DROPDOWN_ERROR: 'Select a Question',
    SENDTO_CHECKBOX_ERROR: 'Select Atleast one',
    KPIDESCRIPTION_EXISTS: 'KPIDescription already exists',
    KPI_SELECT: 'Please select KPI',
    QUESTION_EXITS: 'Question with Checklist Type already exists',
    VALID_VALUE: 'ENTER A VALID VALUE',
    ERROR_OCCURED_SAVING: 'Error Occured While Saving',
    ERROR_OCCURED_GET: 'Error Occured While Fetching Data'
};
